pipeline {
    agent any

    tools {
        nodejs 'NodeJS'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Pemarinzindeolkar/DSO101_02250362.git',
                    credentialsId: 'github-pat'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('A2') {
                    sh '''
                        export PATH=/Users/pema/.nvm/versions/node/v20.20.2/bin:$PATH
                        npm install
                    '''
                }
            }
        }

        stage('Build') {
            steps {
                dir('A2') {
                    sh '''
                        export PATH=/Users/pema/.nvm/versions/node/v20.20.2/bin:$PATH
                        npm run build || echo "No build script defined"
                    '''
                }
            }
        }

        stage('Test') {
            steps {
                dir('A2') {
                    sh '''
                        export PATH=/Users/pema/.nvm/versions/node/v20.20.2/bin:$PATH
                        npm test
                    '''
                }
            }
            post {
                always {
                    junit 'A2/junit.xml'
                }
            }
        }

        stage('Docker Push to Hub') {
            steps {
                script {
                    // Use your existing local image
                    sh """
                        docker tag pemarinzindeolkar17/be-todo:latest pemarinzindeolkar17/be-todo:${BUILD_NUMBER}
                        docker tag pemarinzindeolkar17/be-todo:latest pemarinzindeolkar17/be-todo:jenkins-${BUILD_NUMBER}
                    """
                    
                    // Push to Docker Hub using Jenkins credentials
                    docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-creds') {
                        docker.image("pemarinzindeolkar17/be-todo:${BUILD_NUMBER}").push()
                        docker.image("pemarinzindeolkar17/be-todo:jenkins-${BUILD_NUMBER}").push()
                        docker.image("pemarinzindeolkar17/be-todo:latest").push()
                    }
                    
                    echo "Successfully pushed existing image to Docker Hub"
                    echo "Tags pushed: ${BUILD_NUMBER}, jenkins-${BUILD_NUMBER}, latest"
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline completed successfully!"
            echo "Docker Hub: https://hub.docker.com/r/pemarinzindeolkar17/be-todo"
        }
        failure {
            echo "Pipeline failed. Check the logs above."
        }
    }
}